
    # disable pretty URLS and keep `index.html` & trailing `.html` file references in paths
  prettyURLs = false


# netlify.toml


# Force HTTP â†’ HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Optional: SPA fallback (if you use React, Vue, etc.)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
